// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: analytics.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Edgify {
  public static partial class AnalyticsService
  {
    static readonly string __ServiceName = "edgify.AnalyticsService";

    static readonly grpc::Marshaller<global::Edgify.CreateAnalyticsEventRequest> __Marshaller_edgify_CreateAnalyticsEventRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Edgify.CreateAnalyticsEventRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Edgify.CreateAnalyticsEventResponse> __Marshaller_edgify_CreateAnalyticsEventResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Edgify.CreateAnalyticsEventResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Edgify.CreateAnalyticsEventRequest, global::Edgify.CreateAnalyticsEventResponse> __Method_CreateEvent = new grpc::Method<global::Edgify.CreateAnalyticsEventRequest, global::Edgify.CreateAnalyticsEventResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateEvent",
        __Marshaller_edgify_CreateAnalyticsEventRequest,
        __Marshaller_edgify_CreateAnalyticsEventResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Edgify.AnalyticsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AnalyticsService</summary>
    [grpc::BindServiceMethod(typeof(AnalyticsService), "BindService")]
    public abstract partial class AnalyticsServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Edgify.CreateAnalyticsEventResponse> CreateEvent(global::Edgify.CreateAnalyticsEventRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AnalyticsService</summary>
    public partial class AnalyticsServiceClient : grpc::ClientBase<AnalyticsServiceClient>
    {
      /// <summary>Creates a new client for AnalyticsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AnalyticsServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AnalyticsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AnalyticsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AnalyticsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AnalyticsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Edgify.CreateAnalyticsEventResponse CreateEvent(global::Edgify.CreateAnalyticsEventRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Edgify.CreateAnalyticsEventResponse CreateEvent(global::Edgify.CreateAnalyticsEventRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Edgify.CreateAnalyticsEventResponse> CreateEventAsync(global::Edgify.CreateAnalyticsEventRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Edgify.CreateAnalyticsEventResponse> CreateEventAsync(global::Edgify.CreateAnalyticsEventRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateEvent, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AnalyticsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AnalyticsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AnalyticsServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateEvent, serviceImpl.CreateEvent).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AnalyticsServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateEvent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Edgify.CreateAnalyticsEventRequest, global::Edgify.CreateAnalyticsEventResponse>(serviceImpl.CreateEvent));
    }

  }
}
#endregion
